CHANNEL_ID_RAW = 0
WRITE_API_KEY_RAW = "YOUR_WRITE_API_KEY_RAW"
READ_API_KEY_RAW = "YOUR_READ_API_KEY_RAW"

CHANNEL_ID_RESULTS = 0
WRITE_API_KEY_RESULTS = "YOUR_WRITE_API_KEY_RESULTS"
READ_API_KEY_RESULTS = "YOUR_READ_API_KEY_RESULTS"
